"use client";

import { Check } from "lucide-react";

const card = { border: "1px solid #E0E0E0" } as const;

/** Right-hand explainer shown beside the request form. */
export function WhatHappensNext() {
  const steps = [
    { title: "We call you", body: "To understand the trial and your site.", who: "EcoGlobe · within 2 days" },
    { title: "We confirm with the seller", body: "Availability, dates and how it loads.", who: "EcoGlobe" },
    { title: "We work out the movement", body: "With our logistics partners, for your lane and equipment.", who: "EcoGlobe" },
    { title: "You decide with full costs", body: "Nothing is committed until you have seen everything in writing.", who: "You decide" },
  ];
  return (
    <section className="rounded-2xl bg-white p-6" style={card} aria-labelledby="pilot-next-heading">
      <h2 id="pilot-next-heading" className="text-xs font-bold uppercase tracking-[0.18em] text-neutral-500">
        What happens next
      </h2>
      <ol className="mt-5 flex flex-col gap-5">
        {steps.map((step, index) => (
          <li key={step.title} className="flex gap-3">
            <span className="mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-full bg-neutral-900 text-xs font-bold text-white" aria-hidden="true">
              {index + 1}
            </span>
            <div>
              <p className="text-base font-bold text-neutral-900">{step.title}</p>
              <p className="mt-0.5 text-sm text-neutral-600">{step.body}</p>
              <p className={`mt-1 text-xs font-bold uppercase tracking-[0.14em] ${index === 3 ? "text-neutral-500" : "text-green-800"}`}>{step.who}</p>
            </div>
          </li>
        ))}
      </ol>
    </section>
  );
}

/** Right-hand checklist shown beside the scheduler. */
export function BeforeWeSpeak() {
  const items = [
    "We confirm availability and dates with the seller",
    "We check how the material loads and what equipment suits both sites",
    "We start pricing the lane with our logistics partners",
  ];
  return (
    <section className="rounded-2xl bg-white p-6" style={card} aria-labelledby="pilot-before-heading">
      <h2 id="pilot-before-heading" className="text-xs font-bold uppercase tracking-[0.18em] text-neutral-500">
        Before we speak
      </h2>
      <ul className="mt-5 flex flex-col gap-4">
        {items.map((item) => (
          <li key={item} className="flex gap-3 text-sm text-neutral-700">
            <span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-green-100 text-green-800" aria-hidden="true">
              <Check className="size-3" strokeWidth={3} />
            </span>
            {item}
          </li>
        ))}
      </ul>
    </section>
  );
}

export function WhyNoOnlinePrice() {
  return (
    <section className="rounded-2xl bg-white p-6" style={card} aria-labelledby="pilot-price-heading">
      <h2 id="pilot-price-heading" className="text-base font-bold text-neutral-900">
        Why we don&apos;t price this online
      </h2>
      <p className="mt-2 text-sm leading-relaxed text-neutral-600">
        Freight at load scale depends on the lane, the equipment, the season and the site. A number generated by a
        website would be wrong, and you would find out at the worst moment. We would rather work it out properly with
        you.
      </p>
    </section>
  );
}

export function YourIdentity({ released, variant = "request" }: { released?: boolean; variant?: "request" | "schedule" }) {
  return (
    <section className="rounded-2xl bg-green-50 p-6" aria-labelledby="pilot-identity-heading">
      <h2 id="pilot-identity-heading" className="text-base font-bold text-green-900">
        Your identity
      </h2>
      <p className="mt-2 text-sm leading-relaxed text-green-900/80">
        {released
          ? "You chose to proceed, so the seller can now see your company name alongside the tonnage and region."
          : variant === "schedule"
            ? "The seller sees the tonnage and the region. Your company name is shared only when you decide to proceed."
            : "The seller sees the tonnage and the region. Your company name is shared only when you decide to proceed."}
      </p>
    </section>
  );
}

export function PilotViewTag({ tone, label, detail }: { tone: "buyer" | "internal"; label: string; detail: string }) {
  return (
    <p className="mb-4 flex flex-wrap items-baseline gap-x-3 gap-y-1 text-sm">
      <span className={`text-xs font-bold uppercase tracking-[0.2em] ${tone === "buyer" ? "text-green-800" : "text-red-800"}`}>{label}</span>
      <span className="text-neutral-500">{detail}</span>
    </p>
  );
}
